server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123

mybatis:
    mapper-locations: classpath*:mybatis/*Mapper.xml

debug: true